### ISSUE TITLE
Create a guide for contributing

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydrus#94] opened 2018-02-16 13:42 UTC
Add a guide to contributing file compiling a list of points people need to keep in mind while adding bugs or patches to the repository.
This can be added as a `CONTRIBUTING.md` file in the `.github/` folder

Let us discuss some points to keep in mind here after which someone can be assigned the task of creating a guide.

**Comment by nityanandagohain** [comment] 2018-02-16 13:52
can I work on this

**Comment by chrizandr** [comment] 2018-02-16 14:45
I would actually prefer that everyone contributes to the guidelines here and we discuss it before someone starts working on it.

**Comment by nityanandagohain** [comment] 2018-02-16 15:03
This is what I have managed till now

### Contribution Best Practices

**Feature Requests and Bug Reports**

* Some newcomers are not accustomed to issue trackers and might try to inform developers on the mailing list, chat or even write private emails about bugs and features, but the right place to do this is: The issue tracker of a project.

* Any bug or feature, please open an issue in the issue tracker right away and indicate if you want to work on it yourself.

* Please include all relevant information when you submit an issue and wherever possible a link, information about the code that has issues and a screenshot.

* When you file a bug report on the issue tracker, make sure you add steps to reproduce it. Especially if that bug is some weird/rare one.

**Branching**

* Always work on a newbranch, never work on the master branch.

* Always keep your branch updated. There are many people who contribute to a repository.

**Commits**

* Write clear meaningful git commit messages. ([How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/))

* Make sure your PR's description contains GitHub's special keyword references that automatically close the related issue when the PR is merged. ([Closing Issues via Pull Requests](https://github.com/blog/1506-closing-issues-via-pull-requests))

**Pull Request**
* Always send pull request to upstream/develop branch and not to the master branch.
* Write a good pull request ([Perfect Pull Request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request))

**Comment by Mec-iS** [comment] 2018-02-16 18:35
https://github.com/mapbox/mercantile/blob/master/CODE_OF_CONDUCT.md

Check Contributor Covenant for reference.

**Comment by nityanandagohain** [comment] 2018-02-17 14:14
@Mec-iS should i combine "points people need to keep in mind while adding bugs or patches to the repository."
and code of conduct . Because @chrizandr  stated about that . help me out

**Comment by Mec-iS** [comment] 2018-02-17 14:21
@nityanandagohain These could be two different documents:
* `CODE_OF_CONDUCT.md`
* `CONTRIBUTING.md`

**Comment by nityanandagohain** [comment] 2018-02-17 15:03
@Mec-iS  there is already a code of conduct https://github.com/HTTP-APIs/hydrus/blob/master/.github/CODE_OF_CONDUCT.md

**Closed** 2018-02-24 15:57 UTC
Labels: beginners, enhancement
