### ISSUE TITLE
Uniqueness of IDs

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydrus#215] opened 2018-06-24 15:52 UTC
### I'm submitting a 
- [X] bug report.
- [X] feature request.

### Current Behaviour:
For the purpose of the hydra-agent to identify every node in its graph uniquely and make it point to the right hydrus resource, it cannot rely on database's primary keys as they may change as pk are dropped and substituted. So possibly we need a way to identify every resource instance uniquely in hydrus adn the agent.
For example:
```
{
  "@context": "/api/contexts/Drone.jsonld", 
  "@id": "/api/DroneCollection/2", 
  "@type": "Drone", 
  "DroneID": "2", 
  "MaxSpeed": "300", 
  "Sensor": "Temperature", 
  "State": {
    "@type": "State", 
    "Battery": "81", 
    "Direction": "W", 
    "Position": "0.856901647439813,14.05823948684688", 
    "Speed": "100", 
    "Status": "Confirming"
  }, 
  "model": "xyz", 
  "name": "Drone 1"
}
```
If it happens that this instance is deleted and substituted by another drone (that is a different model or with different maxSpeed for example), it may happen that the same id "2" could be assigned to this new drone creating inconsistency between the data stored in the server and the referenced pk "2" stored in the agent. 

### Expected Behaviour:
Every instance has to be referenced by a unique id, possibly generated by hashing the values of certain properties in the instance

### Discussed solution
We may need to add `"hydra:required": true` for every properties in the Resource that may be considered part of a `UniqueConstraint`, then make the model to create a UniqueConstraint on the properties specified as required. So the server and the client can generate the same checksum by using the values  like `md5(str({"@id": "...", "@type": "", "prop1": "value1", "prop2": "value2"}))`

**Comment by vaibhavchellani** [comment] 2018-06-24 18:12
As far as i can understand the issue is assigning a unique ID to each object so that it can be accessed without fear of inconsistent data . For that the checksum idea is pretty cool , for generating the hash can we consider md5("name+timestamp) , i think this could fairly reduce possible collisions and can be computed quickly.

**Comment by xadahiya** [comment] 2018-06-28 15:52
>  for generating the hash can we consider md5("name+timestamp)
Not every object will have a name property. You can see State or Area data for example. The properties can highly vary and the best way to tackle this is to use some of the object properties ("Required ones") to generate the checksum.

Also, note that we have "required", "writeonly" and "readonly" properties for each class in the APIDoc so it makes sense to implement that mechanism and use it to generate unique IDs or checksums.

**Comment by IamRaviTejaG** [comment] 2018-06-30 08:36
@xadahiya Just my two cents! How about simple using the Python's `uuid` module. It generates a unique ID everytime.

**Comment by Mec-iS** [comment] 2018-06-30 09:39
@xadahiya yeah, that can be a solution that can let the client try to rebuild the uuid in case it needs to uniquely identify something

@IamRaviTejaG yeah, that would be the simplest and safest solution, but the client couldn't never find out what the uuid is

The best solution may be:
```
md5(required_prop1_key|required_prop1_value|...).hexdigest [:12]
```
The problem is, how we define the order of properties.

**Comment by IamRaviTejaG** [comment] 2018-06-30 10:59
@Mec-iS Sorry to ask but is this an issue specific to the GSoCers or is it open to everyone?

**Comment by xadahiya** [comment] 2018-06-30 11:07
@IamRaviTejaG  as these tasks are already assigned to these guys I don't think it makes much sense for you to work on this as well. If you want to contribute you can create some issues and then start working on those or contact us, we can assign some tasks to you :smile:

**Comment by vaibhavchellani** [comment] 2018-07-04 08:08
@Mec-iS @xadahiya can this be closed since i think we have discussed how to implement and we have 
issues #216  #218 #226  that implement this .

**Closed** 2018-07-04 08:32 UTC
Labels: GSOC-2018, bug, enhancement
