### ISSUE TITLE
Basic Implementation Hydra ->Open Api parser

### ISSUE THREAD

**Issue by vaibhavchellani** [HTTP-APIs/hydrus#195] opened 2018-05-18 05:51 UTC
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

Basic implementation of Hydra to Open Api definition , will converts most used objects of both and will generate a YAML file from Hydra Api Doc . 
### Do you want to work on this issue?
Yes !

**Comment by chrizandr** [comment] 2018-05-18 06:36
Duplicate of #193

**Closed by chrizandr** 2018-05-18 06:36 UTC
